### ISSUE TITLE
Inconsistent refresh behavior.

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/profileview#56] opened 2021-07-19 17:08 UTC
The status bar tends not to be updated to reflect when the Active Person focus changes in the Relationships view Profile mode.  And after a drill-down causes the Profile view to show an Event oriented layout instead of the Relationship top layout, switching People can leave the Profile view blank with not recovery option. (Even deleting the View's 3 INI files and then restating Gramps doesn't recover the View's topmost layout.) 

I tried the Example.gramps tree starting with Lewis Anderson Garner von Zieliński, Sr as Home Person. I navigated around various family members. (To populate the "Previous/Next" History) The status bar did not change its contents.

At some point, I clicked the Timeline hotlink for step-sister's "Birth of Garner, Rebecca Catharine" event.  The layout changed to an Event orients layout.  Then I changed Active Person with the Toolbar buttons.  The layout went blank and I couldn't figure out how to get to the main layout again. When I closed Gramps, deleted the .ini files & restarted Gramps, clicking that same Birth event for the Step-sister Rebecca immediately showed that blank view again. And again, I could not get back to the main layout.

Another item about the Refresh as Active Person focus changes: the column settings of Minimized of Expanded are flushed as the focus shifits.  If I collapse the Timeline and click on a sibling, I was expecting the Timeline to be collapsed in newly Active sibling's Profile mode. But it jarringly re-opens.
I don't know how you'd deal with empty columns to avoid the disconcerting redraw, resize of the columns.  Perhaps a Placeholder for empty columns could be inserted to smooth out navigation?

**Comment by cdhorn** [comment] 2021-07-20 03:05
Please read my last response to #45 with regards to navigation history.

The commits tonight added _very_ rough cuts at the remaining missing page views and fixed some other stuff.  Please let me know if you continue to run into blank pages that don't load. If you do and are able to provide steps to reproduce that would be helpful.

Not all objects have links, but you can use double click on any frame with your left mouse button and it should switch to it now. For family view it needs to be that middle portion between the couple where the fact information is displayed.

I think I should be able to add support to update the status bar on object switches, I will try to look at that at some point. 

Every time you switch objects it is a full redraw and the configuration options control the layout hence the groups being expanded again. I agree that is annoying, as is having the header eat space when collapsed. That and similar layout related issues associated with the groups are what I plan on focusing on next.

**Comment by cdhorn** [comment] 2021-07-20 04:11
Status bar should update with last commit now.

**Comment by emyoulation** [comment] 2021-07-20 06:36
The StatusBar now updates. But it doesn't reflected the Preferences option to show the relationship. Although it DOES use the Name format preference.

Note that I just filed a [bug report 12359](https://gramps-project.org/bugs/view.php?id=12359)on the Combined view that doesn't update the StatusBar either. Inquired if there was a standard call for updating the Active Person focus. Noted that update had just been added here without the Relationship data.

**Comment by cdhorn** [comment] 2021-07-20 10:36
Yeah, I saw where it did that in the existing code and did not carry it over. I can add it. I was wondering in my mind if there might be another use for it but was tired and decided to turn in at that point. :-)

**Comment by cdhorn** [comment] 2021-07-20 11:07
I think support added for that option now. It doesn't monitor for changes, if you modify the option with view open it won't take effect till you switch context to someone else.

I prefer to capitalize that string but held back since the base code does not.

**Comment by emyoulation** [comment] 2021-07-20 12:18
> There you have to pick a specific person and I don't have an option to track against the home person, something that I thought maybe I should add although I guess it would be redundant with the status bar so not really necessary.

There's something of a minor ambiguity here.  The Timeline's Relationship annotation is in relation to the **Active*" Person. The StatusBar is in Relation to the **Home** Person. 

The complexity caused by the shift in perspective is unavoidable and informative. It is a tasty & digestible bit of extra context ... but may need stronger decoration to ensure there's no confusion.

**Comment by emyoulation** [comment] 2021-07-25 00:16
Just tested the update from today (about noon July 24th)   

The Status bar is updating and shows relationship to Home Person (thank you)

However, the The **Sidebar and Bottombar focus does not track the Active Person** when using the Previous or Next buttons on the Toolbar (or the A;tLeft/Right arrowkey keysbindings) nor with changing selection using the Go menu.  

The focus DOES correctly track Active Person focus changes with the Home button, clicking a hotlink, Bookmarks, and make Person Active context menu from Person Editor or Clipboard.

**Comment by cdhorn** [comment] 2021-07-25 04:00
Recall this view uses a different navigation history class and as you switch between active object types the navigation type is actually changing as well now. Note the original and the combined relationship views are pinned to Person as the navigation type, but this one navigates across everything so it really makes no sense to do that.

I'm actually not familiar enough with all the Gramps code to know all the ramifications of that, but I suspect there may be more than a few.

**Comment by cdhorn** [comment] 2021-08-29 16:10
Should be resolved in ecbfdb07ae379cfed1178560e2f121751fa7f2bf.

Previous, Next and Go now update the necessary list view history objects.

**Closed by cdhorn** 2021-08-29 16:10 UTC

**Comment by emyoulation** [comment] 2021-08-29 17:43
Noted this PR in the report filed in MantisBT for Nick's Combined mode of the Relationship view.
https://gramps-project.org/bugs/view.php?id=12359

That bug report has not been addressed or assigned. If you could add a programmer's perspective note to that report, it might give him a leg up on the issue... or if there is a view updating simplification that would be appropriate, it might lead to the view management core being tweaked for 6.x
